/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATMku;


import javax.swing.JOptionPane;

/**
 *
 * @author tomama
 */
public class ATMKU extends javax.swing.JFrame {
    public int tab=50000;

    /**
     * Creates new form ATMKU
     */
    public ATMKU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfsaldo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tfisi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfsetor = new javax.swing.JButton();
        tfambil = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMASI SALDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Rp");

        tfsaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfsaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfsaldo.setText("50000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 200, 250, 110);
        jPanel1.getAccessibleContext().setAccessibleName("INFORMASI SALDO");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PENGAMBILAN & PENYETORAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Rp");

        tfsetor.setText("Setor");
        tfsetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsetorActionPerformed(evt);
            }
        });

        tfambil.setText("Ambil");
        tfambil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfambilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tfsetor)
                        .addGap(57, 57, 57)
                        .addComponent(tfambil))
                    .addComponent(tfisi, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfisi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsetor)
                    .addComponent(tfambil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(290, 200, 343, 110);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Petunjuk");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 0, 110, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Keluar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(570, 340, 80, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("   Anjungan Tunai Mandiri - BNI Syariah Bojonegoro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 427, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Download\\image\\muda-menabung-tua-beruntung1.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 660, 410);

        setBounds(0, 0, 664, 432);
    }// </editor-fold>//GEN-END:initComponents

    private void tfambilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfambilActionPerformed
        // TODO add your handling code here:
        int ambil ;
        ambil= Integer.parseInt(tfisi.getText());
        
        if (ambil%100!=0)
            JOptionPane.showMessageDialog(null, "Maaf tidak menyediakan uang logam \n Silahkan ulangi kembali!", "Transaksi gagal",0);
        else if (ambil <50000)
            JOptionPane.showMessageDialog(null,"Besaran minimal pengambilan adalah Rp 50.000,00","ERROR",0);
        else if (ambil >tab)
            JOptionPane.showMessageDialog(null, "Anda berhutang kepada BANK BNI Syariah Kami", "Jangan lupa membayarnya",0);
        {
            tab-=ambil;
            JOptionPane.showMessageDialog(null, "Saldo Anda saat ini sebesar : " + tab);
            tfsaldo.setText(""+tab);
        }
    }//GEN-LAST:event_tfambilActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tfsetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsetorActionPerformed
        // TODO add your handling code here:
        int setor ;
        setor= Integer.parseInt(tfisi.getText());
        
        if (setor%100!=0)
            JOptionPane.showMessageDialog(null, "Maaf tidak menyediakan uang logam \n Silahkan ulangi kembali!", "Transaksi gagal",0);
        else if (setor <50000)
            JOptionPane.showMessageDialog(null,"Besaran minimal penyetoran adalah Rp 50.000,00","ERROR",0);
        else if (setor>=50000)
        {
            tab+=setor;
            JOptionPane.showMessageDialog(null, "Saldo Anda saat ini sebesar : " + tab);
            tfsaldo.setText(""+tab);
        }
    }//GEN-LAST:event_tfsetorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Cara Penggunaan Aplikasi \n [1] Masukkan PIN dengan benar \n [2]"
                            + "Bertransaksilah dengan benar sesuai pilihan \n [3] Gunakan Uang sesuai kebutuhan dan"
                            + "rajinlah menabung \n","INFO",1);
                              
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
  int pin ;
  String str;
   
  str = JOptionPane.showInputDialog(null, "Masukkan 4 Digit PIN Anda:","ATM BNI SYARIAH-BOJONENOGO",0);
  pin = Integer.parseInt(str);
  
  //meghitung kesempatan login
   
  if (pin==1234)
      new ATMKU().setVisible(true);
      }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton tfambil;
    private javax.swing.JTextField tfisi;
    private javax.swing.JTextField tfsaldo;
    private javax.swing.JButton tfsetor;
    // End of variables declaration//GEN-END:variables
}
